language: android

jdk: oraclejdk8

install:
  - yes | sdkmanager "tools" &>/dev/null
  - yes | sdkmanager "platform-tools" &>/dev/null
  - yes | sdkmanager "platforms;android-28" &>/dev/null
  - yes | sdkmanager --update &>/dev/null
  - yes | sdkmanager --licenses &>/dev/null

script: ./gradlew clean assembleDebug --scan -s

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
